name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build, Tag the Docker image, then push to Docker Hub
      env:
        REGISTRY: ${{ secrets.DOCKER_USERNAME }}
        REPOSITORY: sentanapi
        IMAGE_TAG: latest
      run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./webapp/.
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
